export default {
  "allow-uncaught": false,
  "async-only": false,
  bail: false,
  "check-leaks": false,
  color: true,
  delay: false,
  diff: true,
  exit: false,
  extension: ["spec.js"],
  ignore: ["node_modules", "**.cjs"],
  "fail-zero": true,
  "full-trace": true,
  jobs: 1,
  package: "./package.json",
  parallel: true,
  recursive: false,
  require: "chai/expect",
  retries: 2,
  sort: false,
  spec: ["**.spec.js"], 
  timeout: "2000", 
};
