FROM node:current-slim
WORKDIR /app
COPY ./.env.json /app/.env.json
COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock
RUN yarn install --frozen-lockfile
EXPOSE 5000
COPY . .
CMD ["yarn", "test:rest"]